spring.application.name=demo
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=monitor;encrypt=false
spring.datasource.username=monecheck
spring.datasource.password=monecheck

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

watcher.base-path=C:/watch-folder/UAP/000